export const schoolsData = [
  {
    id: 1,
    name: "Lycée de Kigali",
    address: "KG 15 Ave, Kigali",
    email: "info@lyceekigali.edu.rw",
    phone: "+250 788 123 456",
    website: "www.lyceekigali.edu.rw",
    schoolIdentification: true,
    selfAssessment: true,
    hasOrdinaryLevel:true,
    hasAdvancedLevel:true,
    hasBoardingStatus: true,
    province: "Kigali",
    district: "Gasabo"
  },
  {
    id: 2,
    name: "College Saint-André",
    address: "P.O. Box 35, Nyamirambo, Kigali",
    email: "contact@csa.edu.rw",
    phone: "+250 788 234 567",
    website: "www.collegesaintandre.edu.rw",
    schoolIdentification: false,
    selfAssessment: false,
    hasOrdinaryLevel:true,
    hasAdvancedLevel:true,
    hasBoardingStatus: true,
    province: "Kigali",
    district: "Nyarugenge"
  },
  {
    id: 3,
    name: "FAWE Girls School",
    address: "KG 11 Ave, Kigali",
    email: "info@fawe.edu.rw",
    phone: "+250 788 345 678",
    website: "www.fawegirls.edu.rw",
    schoolIdentification: true,
    selfAssessment: true,
    hasOrdinaryLevel:true,
    hasAdvancedLevel:true,
    hasBoardingStatus: true,
    province: "Kigali",
    district: "Kicukiro"
  },
  {
    id: 4,
    name: "Riviera High School",
    address: "KG 8 Ave, Gasabo, Kigali",
    email: "admissions@riviera.edu.rw",
    phone: "+250 788 456 789",
    website: "www.rivierahighschool.edu.rw",
    schoolIdentification: true,
    selfAssessment: false,
    hasOrdinaryLevel:true,
    hasAdvancedLevel:true,
    hasBoardingStatus: true,
    province: "Kigali",
    district: "Gasabo"
  },
  {
    id: 5,
    name: "Groupe Scolaire Officiel de Butare",
    address: "P.O. Box 24, Huye",
    email: "gsob@education.rw",
    phone: "+250 788 567 890",
    website: "www.gsobutare.edu.rw",
    schoolIdentification: false,
    selfAssessment: true,
    hasOrdinaryLevel:true,
    hasAdvancedLevel:true,
    hasBoardingStatus: true,
    province: "Southern Province",
    district: "Huye"
  },
  {
    id: 6,
    name: "Wellspring Academy",
    address: "KG 14 Ave, Nyarutarama, Kigali",
    email: "info@wellspring.edu.rw",
    phone: "+250 788 678 901",
    website: "www.wellspringacademy.edu.rw",
    schoolIdentification: true,
    selfAssessment: true,
    hasOrdinaryLevel:true,
    hasAdvancedLevel:true,
    hasBoardingStatus: true,
    province: "Kigali",
    district: "Gasabo"
  },
  {
    id: 7,
    name: "Green Hills Academy",
    address: "Nyarutarama, Gasabo, Kigali",
    email: "contact@greenhills.edu.rw",
    phone: "+250 788 789 012",
    website: "www.greenhillsacademy.edu.rw",
    schoolIdentification: true,
    selfAssessment: true,
    hasOrdinaryLevel:true,
    hasAdvancedLevel:true,
    hasBoardingStatus: true,
    province: "Kigali",
    district: "Gasabo"
  },
  {
    id: 8,
    name: "College du Christ-Roi",
    address: "P.O. Box 72, Nyanza",
    email: "info@christroi.edu.rw",
    phone: "+250 788 890 123",
    website: "www.christroi.edu.rw",
    schoolIdentification: false,
    selfAssessment: false,
    hasOrdinaryLevel:true,
    hasAdvancedLevel:true,
    hasBoardingStatus: true,
    province: "Southern Province",
    district: "Nyanza"
  },
  {
    id: 9,
    name: "Kagarama Secondary School",
    address: "Kicukiro, Kigali",
    email: "kagarama@education.rw",
    phone: "+250 788 901 234",
    website: "www.kagaram.edu.rw",
    schoolIdentification: false,
    selfAssessment: true,
    hasOrdinaryLevel:true,
    hasAdvancedLevel:true,
    hasBoardingStatus: true,
    province: "Kigali",
    district: "Kicukiro"
  },
  {
    id: 10,
    name: "Ecole Secondaire Apacope",
    address: "P.O. Box 6285, Kigali",
    email: "apacope@education.rw",
    phone: "+250 788 012 345",
    website: "www.apacope.edu.rw",
    schoolIdentification: true,
    selfAssessment: false,
    hasOrdinaryLevel:true,
    hasAdvancedLevel:true,
    hasBoardingStatus: true,
    province: "Kigali",
    district: "Gasabo"
  },
  {
    id: 11,
    name: "Gashora Girls Academy",
    address: "Gashora, Bugesera District, Eastern Province",
    email: "info@gashoragirlsacademy.rw",
    phone: "+250 788 123 450",
    website: "www.gashoragirlsacademy.rw",
    schoolIdentification: true,
    selfAssessment: true,
    hasOrdinaryLevel:true,
    hasAdvancedLevel:true,
    hasBoardingStatus: true,
    province: "Eastern Province",
    district: "Bugesera"
  },
  {
    id: 12,
    name: "College Ami des Enfants",
    address: "KG 676 St, Kibagabaga, Kigali",
    email: "contact@amides.edu.rw",
    phone: "+250 788 234 561",
    website: "www.amides.edu.rw",
    schoolIdentification: false,
    selfAssessment: false,
    hasOrdinaryLevel:true,
    hasAdvancedLevel:true,
    hasBoardingStatus: true,
    province: "Kigali",
    district: "Gasabo"
  },
  {
    id: 13,
    name: "Sonrise High School",
    address: "P.O. Box 147, Musanze",
    email: "sonrisehigh@education.rw",
    phone: "+250 788 345 672",
    website: "www.sonrisehigh.edu.rw",
    schoolIdentification: true,
    selfAssessment: false,
    hasOrdinaryLevel:true,
    hasAdvancedLevel:true,
    hasBoardingStatus: true,
    province: "Northern Province",
    district: "Musanze"
  },
  {
    id: 14,
    name: "Maranyundo Girls School",
    address: "Nyamata, Bugesera District",
    email: "info@maranyundo.edu.rw",
    phone: "+250 788 456 783",
    website: "www.maranyundo.edu.rw",
    schoolIdentification: true,
    selfAssessment: true,
    hasOrdinaryLevel:true,
    hasAdvancedLevel:true,
    hasBoardingStatus: true,
    province: "Eastern Province",
    district: "Bugesera"
  },
  {
    id: 15,
    name: "Groupe Scolaire Remera Rukoma",
    address: "Kamonyi District, Southern Province",
    email: "gsrukoma@education.rw",
    phone: "+250 788 567 894",
    website: "www.gsremerarukoma.edu.rw",
    schoolIdentification: false,
    selfAssessment: false,
    hasOrdinaryLevel:true,
    hasAdvancedLevel:true,
    hasBoardingStatus: true,
    province: "Southern Province",
    district: "Kamonyi"
  },
];