export const SECTOR_DETAILS = {
  CONSTRUCTION_BUILDING_SERVICES: {
    name: "Construction & Building Services",
    icon: "🏗️",
    color: "#FF6B6B",
    description:
      "Learn skills for building construction, plumbing, masonry, and other construction trades.",
  },
  ICT_MULTIMEDIA: {
    name: "ICT & Multimedia",
    icon: "💻",
    color: "#4ECDC4",
    description:
      "Develop expertise in software development, multimedia production, and networking technologies.",
  },
  AGRICULTURE_FOOD_PROCESSING: {
    name: "Agriculture & Food Processing",
    icon: "🌾",
    color: "#8BBF9F",
    description:
      "Gain skills in agriculture, food processing, animal health, and sustainable farming.",
  },
  ENERGY: {
    name: "Energy",
    icon: "⚡",
    color: "#FFD166",
    description:
      "Study electrical technology, renewable energy, and sustainable power solutions.",
  },
  HOSPITALITY_TOURISM: {
    name: "Hospitality & Tourism",
    icon: "🏨",
    color: "#118AB2",
    description:
      "Train for careers in tourism, food services, and hospitality management.",
  },
  ARTS_CRAFTS: {
    name: "Arts & Crafts",
    icon: "🎨",
    color: "#9381FF",
    description:
      "Develop skills in fashion design, performing arts, and creative industries.",
  },
  TECHNICAL_SERVICES: {
    name: "Technical Services",
    icon: "🔌",
    color: "#F46036",
    description:
      "Specialize in electronics, telecommunications, and technical support services.",
  },
  TRANSPORT_LOGISTICS: {
    name: "Transport & Logistics",
    icon: "🚚",
    color: "#5E2F8E",
    description:
      "Learn about automobile technology, logistics, and transportation systems.",
  },
  MANUFACTURING_MINING: {
    name: "Manufacturing & Mining",
    icon: "⚙️",
    color: "#073B4C",
    description:
      "Study manufacturing processes, mining technology, and industrial operations.",
  },
  BEAUTY_AESTHETICS: {
    name: "Beauty & Aesthetics",
    icon: "💇",
    color: "#F72585",
    description:
      "Train in beauty therapy, hair dressing, and personal care services.",
  },
};

export const TVET_DATA = {
  sectors: {
    CONSTRUCTION_BUILDING_SERVICES: [
      "Building Construction",
      "Public Works",
      "Land Surveying",
      "Interior Design",
      "Plumbing Technology",
      "Masonry",
      "Road Construction Machinery Operation",
      "Carpentry",
      "Domestic Plumbing",
      "Painting & Decoration",
    ],
    ICT_MULTIMEDIA: [
      "Software Development",
      "Multimedia Production",
      "Networking and Internet Technologies",
      "Software Programming and Embedded Systems",
      "Computer Systems and Architecture",
      "Computer application_L2",
      "Computer maintenance_L2",
    ],
    AGRICULTURE_FOOD_PROCESSING: [
      "Agriculture",
      "Animal Health",
      "Baking_L1",
      "Baking_L2",
      "Beekeeping and processing_L1",
      "Beekeeping and processing_L2",
      "Cash crop production and Processing_L1",
      "Cash crop production and Processing_L2",
      "Farm machines operation_L1",
      "Farm machines operation_L2",
      "Fish farming and processing_L1",
      "Fish farming and processing_L2",
      "Flower production_L1",
      "Flower production_L2",
      "Food crop production and processing_L1",
      "Food crop production and processing_L2",
      "Food Processing",
      "Forestry",
      "Fruits and vegetables production and processing_L1",
      "Fruits and vegetables production and processing_L2",
      "Leather Technology",
      "Leather works_L1",
      "Leather works_L2",
      "Parks and garden_L1",
      "Parks and garden_L2",
      "Pig production and processing_L1",
      "Pig production and processing_L2",
      "Poultry farming and processing_L1",
      "Poultry farming and processing_L2",
      "Ruminant farming and processing_L1",
      "Ruminant farming and processing_L2",
      "Small scale irrigation_L1",
      "Small scale irrigation_L2",
      "Tree nursery operation_L1",
      "Tree nursery operation_L2",
      "Water and Irrigation",
      "Wood Technology",
    ],
    ENERGY: [
      "Electrical Technology",
      "Renewable Energy",
      "Domestic electricity_L1",
      "Domestic electricity_L2",
      "Solar energy_L1",
      "Solar energy_L2",
      "Peat energy_L1",
      "Peat energy_L2",
      "Biomass and improved cooking stoves_L1",
      "Biomass and improved cooking stoves_L2",
    ],
    HOSPITALITY_TOURISM: [
      "Food And Beverage Operations",
      "Tourism",
      "Front Office & Housekeeping Operations",
      "Housekeeping operations_L1",
      "Housekeeping operations_L2",
      "Food and Beverage Services_L1",
      "Food and Beverage Services_L2",
      "Culinary Arts_L1",
      "Culinary Arts_L2",
    ],
    ARTS_CRAFTS: [
      "Fashion Design",
      "Music and Performing Arts",
      "Fine and Plastic Arts",
      "Tailoring_L1",
      "Tailoring_L2",
      "Graphic arts_L1",
      "Graphic arts_L2",
      "Ceramic and sculpture_L1",
      "Ceramic and sculpture_L2",
    ],
    TECHNICAL_SERVICES: [
      "Electronic and Telecommunication",
      "Electronic Services_L2",
    ],
    TRANSPORT_LOGISTICS: [
      "Automobile Technology",
      "Heavy Machinery",
      "Business Services_L1",
      "Business Services_L2",
      "Motorcycle repair and maintenance_L1",
      "Motorcycle repair and maintenance_L2",
      "Driving_L1",
      "Driving_L2",
    ],
    MANUFACTURING_MINING: [
      "Manufacturing Technology",
      "Mining Technology",
      "Automobile repair and maintenance_L1",
      "Automobile repair and maintenance_L2",
      "Welding_L1",
      "Welding_L2",
      "Automobile Body Works_L1",
      "Automobile Body Works_L2",
      "Small scale Mining_L1",
      "Small scale Mining_L2",
    ],
    BEAUTY_AESTHETICS: [
      "Beauty therapy and Aesthetics",
      "Hair Dressing_L1",
      "Hair Dressing_L2",
    ],
  },
};

// Add this to your utils/tvetData.ts file
